markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Liwenjun Blog
host: irecsys.com
desc: 推荐系统相关文章介绍.

custom:
    category:
        default: Default Category
        another: Another Category
	rsh: Recommender System Handbook
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

      - name:  rsh
        title: Recommender System Handbook

    scrollingLoadCount: 5                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: 李文俊
        email: liwenjun.uestc@gmail.com
        disqus: leewenjun              # Disqus缩略标识
        gcse: 001817902684948621035:u_gc_r1r7na     # Google自定义搜索标识ID
        github: leewenjun                 # GitHub账号
        gravatar: 6b48eaff792f7dcbc7676fedf0497a05  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
